apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: geocodetopicsource
spec:
  bootstrapServers:
  - my-cluster-kafka-bootstrap.amq-streams-kafka.svc:9092
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: surveyadminservice
    uri: "/api/cloudevents/geocodeComplete"
  topics:
  - geocodetopic
