apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: surveyinputservice
spec:
  template:
    spec:
      containers:
      - name: surveyinputservice
        image: image-registry.openshift-image-registry.svc:5000/libertysurvey/surveyinputservice
        imagePullPolicy: Always
        env:
        - name: kafka.bootstrap.servers
          value: my-cluster-kafka-bootstrap.amq-streams-kafka.svc:9092
      timeoutSeconds: 300
