@startuml

title libertyEventDrivenSurvey

skinparam monochrome true
skinparam DefaultTextAlignment center
scale 1.0

actor user1 as "User"

' https://plantuml.com/deployment-diagram
' Arrows: https://plantuml.com/deployment-diagram#bb3fdb917676e9ae
cloud kubernetes as "Kubernetes" {
  collections knativeServing1 as "KNative Serving"
  collections surveyInputService
  stack locationtopic
  collections knativeServing2 as "KNative Eventing"
  collections surveyGeocoderService
  rectangle googleMaps as "Google Maps API"
}

user1 --> knativeServing1 : HTTP
knativeServing1 --^ surveyInputService : HTTP
surveyInputService --# locationtopic : Kafka Emitter
locationtopic #-> knativeServing2 : KafkaSource
knativeServing2 --> surveyGeocoderService : HTTP (CloudEvent)
surveyGeocoderService --> googleMaps
googleMaps --> surveyGeocoderService

@enduml
