@startuml

title libertyEventDrivenSurvey

skinparam monochrome true
skinparam DefaultTextAlignment center
scale 1.0

actor user as "User"
actor admin as "Administrator"

' https://plantuml.com/deployment-diagram
' Arrows: https://plantuml.com/deployment-diagram#bb3fdb917676e9ae
cloud kubernetes as "Kubernetes" {
  collections knativeServing1 as "KNative Serving"
  collections surveyInputService as "surveyInputService (0..∞)"
  stack locationtopic
  collections knativeServing2 as "KNative Eventing"
  collections surveyGeocoderService as "surveyGeocoderService (0..∞)"
  rectangle googleMaps as "Google Maps API"
  stack geocodetopic
  collections knativeServing3 as "KNative Eventing"
  collections surveyAdminService as "surveyAdminService (1..1)"
}

user --> knativeServing1 : HTTP
knativeServing1 --^ surveyInputService : HTTP
surveyInputService --# locationtopic : Kafka Emitter
locationtopic #-> knativeServing2 : KafkaSource
knativeServing2 --> surveyGeocoderService : HTTP (CloudEvent)
surveyGeocoderService --> googleMaps
googleMaps --> surveyGeocoderService
surveyGeocoderService ---# geocodetopic : Kafka Emitter
geocodetopic #-> knativeServing3 : KafkaSource
knativeServing3 --> surveyAdminService : HTTP (CloudEvent)
surveyAdminService --> admin

@enduml
