# Copyright 2023 IBM Corp. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

FROM icr.io/appcafe/websphere-liberty:full-java17-openj9-ubi

# These defaults are overridden by `--build-arg` arguments in pom.xml
ARG NAME=placeholder
ARG VERSION=0.0.0
ARG REVISION=placeholder
ARG AUTHORS=placeholder@example.com
ARG VENDOR=Placeholder
ARG SUMMARY=Placeholder
ARG DESCRIPTION=Placeholder
ARG URL=https://example.com/
ARG SOURCE=https://example.com/
# https://spdx.org/licenses/
ARG LICENSE="Apache-2.0"
ARG VERBOSE=false
ARG OPENJ9_SCC=true
ARG OPENJ9_JAVA_OPTIONS=""
ARG CONSOLE_FORMAT="simple"
ARG CHECKPOINT_TYPE="beforeAppStart"

# https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
LABEL \
  org.opencontainers.image.authors="${AUTHORS}" \
  org.opencontainers.image.vendor="${VENDOR}" \
  org.opencontainers.image.url="${URL}" \
  org.opencontainers.image.source="${SOURCE}" \
  org.opencontainers.image.version="${VERSION}" \
  org.opencontainers.image.revision="${REVISION}" \
  vendor="${VENDOR}" \
  name="${NAME}" \
  org.opencontainers.image.title="${NAME}" \
  version="${VERSION}-${REVISION}" \
  summary="${SUMMARY}" \
  description="${DESCRIPTION}" \
  org.opencontainers.image.description="${DESCRIPTION}" \
  maintainer="${AUTHORS}" \
  org.opencontainers.image.authors="${AUTHORS}" \
  org.opencontainers.image.licenses="${LICENSE}" \
  license="${LICENSE}"

COPY --chown=default:root target/liberty/wlp/usr/servers/surveyAdminService/server.xml /config/server.xml

RUN features.sh

COPY --chown=default:root target/liberty/wlp/usr/servers/surveyAdminService/jvm.options /config/jvm.options
COPY --chown=default:root target/liberty/wlp/usr/servers/surveyAdminService/bootstrap.properties /config/bootstrap.properties
COPY --chown=default:root target/surveyAdminService.war /config/apps

# Maven generates a variables file that will override the defaults
COPY --chown=default:root target/liberty/wlp/usr/servers/surveyAdminService/configDropins/overrides/liberty-plugin-variable-config.xml /config/configDropins/overrides/

ENV WLP_LOGGING_CONSOLE_FORMAT=${CONSOLE_FORMAT}

# This script will add the requested XML snippets, grow image to be fit-for-purpose and apply interim fixes
RUN configure.sh

RUN checkpoint.sh ${CHECKPOINT_TYPE}
